# Generated by Django 3.2.4 on 2021-06-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.IntegerField(choices=[('1', 'Easy'), ('2', 'Medium'), ('3', 'Hard')]),
        ),
    ]
